% Produced by CVXGEN, 2021-01-22 10:01:18 -0500.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
J = params.J;
Sigma = params.Sigma;
a_max = params.a_max;
dotq_max = params.dotq_max;
dotq_min = params.dotq_min;
dotq_prev = params.dotq_prev;
h_goal = params.h_goal;
sigma = params.sigma;
sigma_0 = params.sigma_0;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable dotq(6, 1);

  minimize(quad_form(dotq, eye(6)));
  subject to
    -(sigma' - sigma_0')*J*dotq >=  - h_goal - (sigma' - sigma_0')*Sigma;
    dotq_min <= dotq;
    dotq <= dotq_max;
    -a_max <= dotq - dotq_prev;
    dotq - dotq_prev <= a_max;
cvx_end
vars.dotq = dotq;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
